apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv1
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: slow
  capacity:
    storage: 5Gi
  hostPath:
    path: /media/vladimir/addition/pv1