apiVersion: v1
kind: Service
metadata:
  name: redmine-service
  namespace: lesson-5
spec:
  type: NodePort
  selector:
    app: redmine
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 30002